### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by constfun** [chetmurthy/typpx#1]
Original code seems to be LGPL https://gitlab.com/camlspotter/typpx/-/blob/hg-b1.4.0/_oasis#L6

**Comment by chetmurthy** [comment]
Oops, thanks for spotting this.  Originally I'd hoped the author (Jun) would take back these fixes, but he seems to have moved on to other things, so I guess I should at least clean things up.

**Comment by chetmurthy** [comment]
all done!  Thanks again!
